### ISSUE TITLE
Merge en.bootstrap.yml contents into en.yml

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#102]
- copy strings under `en:` from `config/locales/en.bootstrap.yml` to `config/locales/en.yml`
- delete `config/locales/en.bootstrap.yml` file
- create a pull request with the changes mentioned

---

More on localization for Ruby on Rails: https://guides.rubyonrails.org/i18n.html
_Key words: i18n, internationalization, localization_

**Comment by rk-1620** [comment]
@rakvium I would like to work on it. Please assign it to me.

**Comment by rakvium** [comment]
> @rakvium I would like to work on it. Please assign it to me.

@rk-1620, assigned

**Comment by rakvium** [comment]
Done as #103 by @rk-1620
