### ISSUE TITLE
Add Lithuanian locale for Lithuanian language support

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#106]
- add `lt.yml` locale file to `config/locales`
- copy https://github.com/rakvium/blog/blob/master/config/locales/en.yml content into it
- replace English translations in `lt.yml` file with Lithuanian ones
- add `lt` into array of available locales in https://github.com/rakvium/blog/blob/master/config/application.rb
- submit a pull request with your changes
- get the tests pass

Notice: `language_name` string would be for Lithuanian language name in Lithuanian

---

More on localization for Ruby on Rails: https://guides.rubyonrails.org/i18n.html
_Key words: i18n, internationalisation, internationalization, Lithuanian, localisation, localization_

**Comment by mantasio** [comment]
Hey @rakvium, I can help with this, could you please assign it to me?

**Comment by rakvium** [comment]
@mantasio of course, thank you in advance!

**Comment by rakvium** [comment]
Done by @mantasio in #110
