### ISSUE TITLE
Add Spanish locale to support Spanish language

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#108]
- add `es.yml` locale file to `config/locales`
- copy https://github.com/rakvium/blog/blob/master/config/locales/en.yml content into it
- replace English translations in `es.yml` file with Spanish ones
- add `es` into array of available locales in https://github.com/rakvium/blog/blob/master/config/application.rb
- submit a pull request with your changes
- get the tests pass

Notice: `language_name` string would be for Spanish language name in Spanish

---

More on localization for Ruby on Rails: https://guides.rubyonrails.org/i18n.html
_Key words: Castellano, Castilian, Español, i18n, internationalisation, internationalization, localisation, localization, Spanish_

**Comment by taicoding** [comment]
Hi there, I'm a native spanish speaker and I would like to work on this issue. Please assign it to me.

**Comment by rakvium** [comment]
@taicoding you're welcome and thank you in advance!

**Comment by rakvium** [comment]
Resolved in #109 by @taicoding
