### ISSUE TITLE
Remove Travis CI build badge from the project

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#131]
As far as [Travis CI practically discontinued their free tier](https://www.travis-ci.com/blog/2020-11-02-travis-ci-new-billing/), and the project already uses GitHub Actions for CI, there is no reason to keep the Travis build badge in the project's description.

This badge is [currently located](https://github.com/rakvium/blog/blob/0e2fd56f44685b9c1ec502cdafd7764c4bea4ffe/README.md) in [README.md](https://github.com/rakvium/blog/blob/master/README.md) file and it looks like this:
[![Build Status](https://travis-ci.org/rakvium/blog.svg?branch=master)](https://travis-ci.org/rakvium/blog)
In case the image above is not accessible anymore, at the moment of the issue creation it basically says `build|unknown` as.

The simplest way to clear this task is to:
- navigate to [README.md](https://github.com/rakvium/blog/blob/master/README.md) file
- remove `[![Build Status](https://travis-ci.org/rakvium/blog.svg?branch=master)](https://travis-ci.org/rakvium/blog)` line from it
- press `Commit Changes...` button to create a pull request

**Comment by shubhampaliwal3011** [comment]
Hey @rakvium, I would like to work on this.

**Comment by rakvium** [comment]
Resolved by #132
