### ISSUE TITLE
Resolve grammar mistakes in README.md

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#133]
[At the moment](https://github.com/rakvium/blog/blob/494b37fc20ee9e2c0e49df95464d04c27ba24376/README.md) README.md file has some grammar mistakes.
It would be great to read it out and resolve them.

The simplest way to clear this task is to:
- navigate to [README.md](https://github.com/rakvium/blog/blob/master/README.md) file
- resolve the grammar mistakes by editing the file right on GitHub
- press `Commit Changes...` button to create a pull request

**Comment by rakvium** [comment]
@deatheguard would you mind clearing it out?

**Comment by deatheguard** [comment]
> @deatheguard would you mind clearing it out?

Absolutely, you got it
