### ISSUE TITLE
Remove Travis CI config file from the project

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#138]
As far as [Travis CI practically discontinued their free tier](https://www.travis-ci.com/blog/2020-11-02-travis-ci-new-billing/), and the project already uses GitHub Actions for CI, there is no reason to keep the Travis CI config file in the project.

This file is [currently located in the root directory of the project](https://github.com/rakvium/blog/blob/0e2fd56f44685b9c1ec502cdafd7764c4bea4ffe/.travis.yml).

The simplest way to clear this task is to:
- navigate to [.travis.yml](https://github.com/rakvium/blog/blob/master/.travis.yml) file
- click on `...` (More file actions) button
- click on `Delete file`
- press `Commit Changes...` button to create a pull request

**Comment by krishna16sharma** [comment]
I can do this for you. Please assign it to me.
