### ISSUE TITLE
Remove ru.yml locale support

### ISSUE THREAD

**Issue by sudakov-eugene** [rakvium/blog#83]
Due to [russian invasion into Ukraine](https://stand-with-ukraine.pp.ua/) there is no point to support russian locale anymore.

To drop the support:
- [x] remove `ru.yml` locale file from `config/locales`
- [x] remove `ru` from array of available locales in https://github.com/rakvium/blog/blob/master/config/application.rb
- [x] submit a pull request with your changes
- [x] get the tests pass

**Comment by sudakov-eugene** [comment]
@rakvium  :slightly_smiling_face:

**Comment by rakvium** [comment]
@sudakov-eugene I have no good reason to reject this proposition, so please go on ☝️

**Comment by rakvium** [comment]
Done in #97 by @deatheguard
