### ISSUE TITLE
Merge authentication.en.yml contents into en.yml 

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#92]
- copy strings under `en:` from `config/locales/authentication.en.yml` to `config/locales/en.yml`
- delete `config/locales/authentication.en.yml` file
- create a pull request with the changes mentioned

---

More on localization for Ruby on Rails: https://guides.rubyonrails.org/i18n.html
_Key words: i18n, internationalization, localization_

**Comment by dNhunter3107** [comment]
Please assign this issue to me.

**Comment by rakvium** [comment]
@dNhunter3107 assigned ✅

**Comment by rakvium** [comment]
@dNhunter3107 thank you, well done!
