### ISSUE TITLE
Add German (Deutsch) locale

### ISSUE THREAD

**Issue by rakvium** [rakvium/blog#93]
- add `de.yml` locale file to `config/locales`
- copy https://github.com/rakvium/blog/blob/master/config/locales/en.yml content into it
- replace `en:` in the start of `de.yml` file with `de:`
- replace English translations in `de.yml` file with German ones
- add `de` into array of available locales in https://github.com/rakvium/blog/blob/master/config/application.rb
- submit a pull request with your changes
- make sure the tests pass

Notice: `language_name` string would be for German language name in Deutsch

---

More on localization for Ruby on Rails: https://guides.rubyonrails.org/i18n.html
_Key words: German, Deutsch, Deutsche Sprache, i18n, internationalization, localization_

**Comment by m1ga** [comment]
Can help you here!
